CREATE DATABASE IF NOT EXISTS userDB;
USE userDB;

CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT NOT NULL, fname VARCHAR(100) NOT NULL, lname VARCHAR(100) NOT NULL, phrase VARCHAR(100) NOT NULL, PRIMARY KEY(id));
